name: Cypress Tests

# Trigger the workflow on push or pull request to the main branch
on:
  workflow_dispatch:

jobs:
  cypress:
    # Define the runner environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get Tag
      id: get_tag
      run: echo "Daria"
